export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const START_INITIALIZATION = 'START_INITIALIZATION';

export const SET_THEME = 'SET_THEME';
export const TOGGLE_BOTTOM_SHEET = 'TOGGLE_BOTTOM_SHEET';
export const TOGGLE_SNACKBAR = 'TOGGLE_SNACKBAR';

export const FETCH_USER_DOC = 'FETCH_USER_DOC';
export const FETCH_USER_EXPENSES = 'FETCH_USER_EXPENSES';
export const FETCH_USER_EXPENSES_CATEGORIES = 'FETCH_USER_EXPENSES_CATEGORIES';
export const FETCH_USER_INCOMES = 'GET_USER_INCOMES';
export const FETCH_USER_INCOMES_CATEGORIES = 'FETCH_USER_INCOMES_CATEGORIES';
